### ISSUE TITLE
Instructions for newbies

### ISSUE THREAD

**Issue by gforcada** [glasswalk3r/jenkins-translation-tool#7]
Hi! 😄 

I [was pointed](https://github.com/jenkinsci/jenkins/pull/7498) to this tool if I wanted to contribute to Jenkins core translations.

I'm not a java nor a perl developer, so I'm a bit confused on what I'm expected to do with this repository 😅 

I have cloned jenkins repo and this one, managed to install cpan on my fedora laptop and then I did run `perl Makefile.PL` for later run `make` ✨ 

Now I see I have a `bin/jtt` but somehow it keeps telling me that there are missing dependencies 🤔 

Would it be possible to write/expand the existing documentation with a few more tips on how to get the system running? 🤞🏾

**Comment by glasswalk3r** [comment]
Hello there,

Well, actually you missed the very instruction in the project README that would avoid leaving you with an incomplete setup.

I moved those instructions to the [top of the page](https://github.com/glasswalk3r/jenkins-translation-tool#install), try to follow up from there.

Also, take a look at the [recommended workflow](https://github.com/glasswalk3r/jenkins-translation-tool/blob/main/Workflow.md).

A caveat: even though you're not a programmer, knowing the basics of git will be necessary.

**Comment by gforcada** [comment]
Hi!

Oh, actually I am a developer, for ~15 years already 👴🏾 😆 

What I haven't done within those 15 years is doing any Perl 😅  I did saw that `cpan Jenkins::i18n` and actually ran it.

Still after doing all that I don't really know how to run this project...

In short what I did was:

```
git clone jenkins
git clone jenkins-translation-tool
cd jenkins-translation-tool
cpan Jenkins::i18n
???
```

Oh, now it I see, I did not do the `cpan Jenkins:i18n` __inside__ the `jenkins-translation-tool` 😅 

Ok, and then going to the jenkins repository and running `perl ../jenkins-translation-tool/bin/jtt --lang=ca` it does work ✨ 

Maybe this more step-by-step should be added somewhere? 😄

**Comment by glasswalk3r** [comment]
> What I haven't done within those 15 years is doing any Perl sweat_smile

If you're doing development for all this time in a UNIX-like operation system, yes, you were regularly using Perl applications, just didn't know about.

> I did saw that `cpan Jenkins::i18n` and actually ran it.

`cpan` is the standard client (that comes by default with a Perl installation) that manages distributions and dependencies automatically. `cpanm` is considered a more modern approach but the result at the end is exactly the same when using the standard configurations.

Just for the sake of comparison, `cpan` does the same that `pip`, `npm`, `mvn`, `gradle`, `bundle` does (at least if you consider the feature of downloading reusable code from the internet).

`Jenkins::i18n` is the name of the Perl distribution at CPAN that takes care of installing everything required, including the `jtt` CLI.

See https://www.perl.org/cpan.html.

> Still after doing all that I don't really know how to run this project...
> 
> In short what I did was:
> 
> ```
> git clone jenkins
> git clone jenkins-translation-tool
> cd jenkins-translation-tool
> cpan Jenkins::i18n
> ???
> ```

No, you're doing the wrong way, unless you want to see the source code and mess with it, `cpan` is the only thing  you need to use `jtt`.

> Oh, now it I see, I did not do the `cpan Jenkins:i18n` **inside** the `jenkins-translation-tool` sweat_smile

This is isn't required either.

> Ok, and then going to the jenkins repository and running `perl ../jenkins-translation-tool/bin/jtt --lang=ca` it does work sparkles
> 
> Maybe this more step-by-step should be added somewhere? smile

Honestly, all that I explained here is also available at https://github.com/glasswalk3r/jenkins-translation-tool#detailed-description.
